export const AUTH = {
  LOGIN: "AUTH_LOGIN",
  LOGOUT: "AUTH_LOGOUT",
  REGISTER: "AUTH_REGISTER",
  CHECK: "AUTH_CHECK",
  SET: "AUTH_SET",
  EDIT: "AUTH_EDIT",
};

export const PROFILE = {
  FETCH: "PROFILE_FETCH",
  TOGGLE_FOLLOW: "PROFILE_TOGGLE_FOLLOW",
};

export const ARTICLE = {
  FETCH: "ARTICLE_FETCH",
  FETCH_ALL: "PROFILE_FETCH_ALL",
  FETCH_FOLLOW: "PROFILE_FETCH_FOLLOW",
  EDIT: "ARTICLE_EDIT",
  POST: "ARTICLE_POST",
  DELETE: "ARTICLE_DELETE",
  TOGGLE_FAVORITE: "ARTICLE_TOGGLE_FAVORITE",
  TOGGLE_ONE_FAVORITE: "ARTICLE_TOGGLE_ONE_FAVORITE",
  TOGGLE_FOLLOW: "ARTICLE_TOGGLE_FOLLOW",
};

export const TOKEN = {
  SET: "TOKEN_SET",
  REMOVE: "TOKEN_REMOVE",
};

export const TAGS = {
  GET: "TAGS_GET",
};

export const FAVORITE = {
  ADD: "FAVORITE_ADD",
  DELETE: "FAVORITE_DELETE",
};

export const COMMENT = {
  FETCH: "COMMENT_FETCH",
  CREATE: "COMMENT_CREATE",
  DELETE: "COMMENT_DELETE",
};
